"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Download, Share2, Trash2, X, ExternalLink } from "lucide-react"
import { Dialog, DialogContent } from "@/components/ui/dialog"
import { useToast } from "@/components/ui/use-toast"
import { useI18n } from "@/lib/i18n"
import type { GeneratedImage } from "@/lib/chat-store"

interface ImageGalleryProps {
  images: GeneratedImage[]
  onDelete: (id: string) => void
}

export function ImageGallery({ images, onDelete }: ImageGalleryProps) {
  const [selectedImage, setSelectedImage] = useState<GeneratedImage | null>(null)
  const { toast } = useToast()
  const { t } = useI18n()

  const handleDownload = async (image: GeneratedImage) => {
    try {
      const response = await fetch(image.url)
      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `anbu-ai-${image.id}.png`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)
      toast({ description: t("imageDownloaded") })
    } catch (error) {
      // Fallback: open in new tab
      window.open(image.url, "_blank")
    }
  }

  const handleShare = async (image: GeneratedImage) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "Generated by Anbu AI",
          text: image.prompt,
          url: image.url,
        })
      } catch (error) {
        // User cancelled or share failed
      }
    } else {
      await navigator.clipboard.writeText(image.url)
      toast({ description: "Image URL copied to clipboard" })
    }
  }

  if (images.length === 0) {
    return <div className="flex items-center justify-center h-48 text-muted-foreground">No images generated yet</div>
  }

  return (
    <>
      <ScrollArea className="h-[400px]">
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 p-1">
          {images.map((image) => (
            <Card
              key={image.id}
              className="group relative overflow-hidden cursor-pointer"
              onClick={() => setSelectedImage(image)}
            >
              <img
                src={image.url || "/placeholder.svg"}
                alt={image.prompt}
                className="w-full aspect-square object-cover transition-transform group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                <Button
                  size="icon"
                  variant="secondary"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleDownload(image)
                  }}
                >
                  <Download className="h-4 w-4" />
                </Button>
                <Button
                  size="icon"
                  variant="secondary"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleShare(image)
                  }}
                >
                  <Share2 className="h-4 w-4" />
                </Button>
                <Button
                  size="icon"
                  variant="secondary"
                  onClick={(e) => {
                    e.stopPropagation()
                    onDelete(image.id)
                  }}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
              <div className="absolute bottom-0 left-0 right-0 p-2 bg-gradient-to-t from-black/80 to-transparent">
                <p className="text-xs text-white truncate">{image.prompt}</p>
              </div>
            </Card>
          ))}
        </div>
      </ScrollArea>

      {/* Full-screen preview */}
      <Dialog open={!!selectedImage} onOpenChange={() => setSelectedImage(null)}>
        <DialogContent className="max-w-4xl p-0 bg-black/95">
          {selectedImage && (
            <div className="relative">
              <Button
                size="icon"
                variant="ghost"
                className="absolute top-2 right-2 z-10 text-white hover:bg-white/20"
                onClick={() => setSelectedImage(null)}
              >
                <X className="h-4 w-4" />
              </Button>
              <img
                src={selectedImage.url || "/placeholder.svg"}
                alt={selectedImage.prompt}
                className="w-full h-auto max-h-[80vh] object-contain"
              />
              <div className="p-4 bg-black/80">
                <p className="text-sm text-white mb-2">{selectedImage.prompt}</p>
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <span>Style: {selectedImage.style}</span>
                  <span>•</span>
                  <span>Size: {selectedImage.size}</span>
                </div>
                <div className="flex items-center gap-2 mt-4">
                  <Button size="sm" onClick={() => handleDownload(selectedImage)}>
                    <Download className="h-4 w-4 mr-2" />
                    {t("download")}
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => handleShare(selectedImage)}>
                    <Share2 className="h-4 w-4 mr-2" />
                    {t("share")}
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => window.open(selectedImage.url, "_blank")}>
                    <ExternalLink className="h-4 w-4 mr-2" />
                    Open
                  </Button>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  )
}
